from enum import Enum


class SkannedVulnerabilityType(Enum):
    COOKIE_SECURE = 1
    COOKIE_SAME_SITE = 2
    COOKIE_HTTP_ONLY = 3

    HEADER_X_CONTENT_TYPE_OPTIONS = 4
    HEADER_HSTS_SET = 11
    HEADER_HSTS_SUBDOMAIN = 12

    HEADER_LEAK_X_POWERED_BY = 13
    HEADER_LEAK_X_BACKEND_SERVER = 14
    HEADER_LEAK_X_ASPNET_VERSION = 15

    CONFIG_FILE_EXPOSURE_HTACCESS = 5
    CONFIG_FILE_EXPOSURE_ENV = 6
    CONFIG_FILE_EXPOSURE_GIT = 7
    # CONFIG_FILE_EXPOSURE_HTACCESS = 8

    JWT_WELL_KNOWN_SECRET = 30
    JWT_NO_VERIFICATION = 31
    JWT_SELF_SIGNED_INJECT = 32
    # JWT_WELL_KNOWN_SECRET = 33
    # JWT_WELL_KNOWN_SECRET = 34
    # JWT_WELL_KNOWN_SECRET = 35



    HTTP_SCHEME_USAGE = 9
    HTTP_REDIRECT = 10

    CORS_SET = 20
    CORS_ALL_ALLOWED = 21
    CONTENT_TYPE_OPTIONS = 23
    CONTENT_TYPE_OPTIONS_NOSNIFF = 24

    CONNECT_COMPROMISED_SITE = 22

    INFO_IP_ADDRESS = 40
    INFO_OPEN_PORT = 41
    INFO_SERVER_INFRA_HOSTING_PROVIDER = 42
    INFO_SERVER_INFRA_LOAD_BALANCE = 43
    INFO_SERVER_INFRA_TLS = 44
    INFO_SERVER_SOFTWARE = 45

    ATTACK_SERVER_SLOWLORIS = 47